import type { FeedItem, Store } from "./types";

// Datos mock. Centralizados y tipados para reemplazo directo por Supabase
// cuando exista backend real (ver LOOP_01.md).

export const stores: Record<string, Store> = {
  nova: {
    id: "nova",
    name: "Nova Studio",
    avatarUrl: "https://i.pravatar.cc/64?img=32",
    verified: true,
    distanceKm: 1.2,
    whatsappNumber: "573001234567",
    rating: 0,
    followers: 3200,
  },
  luma: {
    id: "luma",
    name: "Luma Perfumería",
    avatarUrl: "https://i.pravatar.cc/64?img=47",
    verified: true,
    distanceKm: 3.8,
    whatsappNumber: "573007654321",
    rating: 0,
    followers: 5100,
  },
  terra: {
    id: "terra",
    name: "Terra Calzado",
    avatarUrl: "https://i.pravatar.cc/64?img=15",
    distanceKm: 0.6,
    whatsappNumber: "573009988776",
    rating: 0,
    followers: 1800,
  },
  orbe: {
    id: "orbe",
    name: "Órbita Tech",
    avatarUrl: "https://i.pravatar.cc/64?img=60",
    verified: true,
    whatsappNumber: "573005544332",
    rating: 0,
    followers: 6400,
  },
  casa: {
    id: "casa",
    name: "Casa Cálida",
    avatarUrl: "https://i.pravatar.cc/64?img=25",
    distanceKm: 5.4,
    whatsappNumber: "573002211334",
    rating: 0,
    followers: 940,
  },
};

export const feedItems: FeedItem[] = [
  {
    id: "f1",
    type: "PRODUCT_POST",
    category: "Moda",
    store: stores.nova,
    images: [
      "https://picsum.photos/seed/nova-jacket-1/800/1000",
      "https://picsum.photos/seed/nova-jacket-2/800/1000",
    ],
    badge: "Nuevo",
    product: {
      id: "p1",
      name: "Chaqueta oversize acolchada",
      price: 189000,
      currency: "COP",
      availability: "in_stock",
      rating: 0,
    },
    likes: 214,
  },
  {
    id: "f2",
    type: "INSPIRATIONAL_POST",
    category: "Perfumería",
    store: stores.luma,
    images: ["https://picsum.photos/seed/luma-social-1/800/900"],
    caption:
      "Así se ve nuestro rincón de fragancias en la tienda física esta semana.",
    product: {
      id: "p2",
      name: "Eau de Parfum Ámbar 50ml",
      price: 132000,
      currency: "COP",
      availability: "in_stock",
    },
    likes: 96,
  },
  {
    id: "f3",
    type: "PRODUCT_POST",
    category: "Calzado",
    store: stores.terra,
    images: [
      "https://picsum.photos/seed/terra-shoes-1/800/1000",
      "https://picsum.photos/seed/terra-shoes-2/800/1000",
      "https://picsum.photos/seed/terra-shoes-3/800/1000",
    ],
    badge: "Pocas unidades",
    product: {
      id: "p3",
      name: "Botas urbanas cuero",
      price: 245000,
      currency: "COP",
      availability: "low_stock",
      rating: 0,
    },
    likes: 158,
  },
  {
    id: "f4",
    type: "PRODUCT_POST",
    category: "Tecnología",
    store: stores.orbe,
    images: ["https://picsum.photos/seed/orbe-tech-1/800/1000"],
    product: {
      id: "p4",
      name: "Audífonos inalámbricos ANC",
      price: 310000,
      currency: "COP",
      availability: "in_stock",
      rating: 0,
    },
    likes: 341,
  },
  {
    id: "f5",
    type: "INSPIRATIONAL_POST",
    category: "Hogar",
    store: stores.casa,
    images: ["https://picsum.photos/seed/casa-social-1/800/900"],
    caption: "Nueva colección de velas para diciembre, huelen increíble.",
    product: {
      id: "p5",
      name: "Vela artesanal ámbar y vainilla",
      price: 48000,
      currency: "COP",
      availability: "in_stock",
    },
    likes: 72,
  },
  {
    id: "f6",
    type: "PRODUCT_POST",
    category: "Moda",
    store: stores.nova,
    images: ["https://picsum.photos/seed/nova-bag-1/800/1000"],
    product: {
      id: "p6",
      name: "Bolso mini estructurado",
      price: 156000,
      currency: "COP",
      availability: "out_of_stock",
      rating: 0,
    },
    likes: 289,
  },
  // ---- LOOP 07: PROMOTION, COLLECTION, STORE_STORY ----
  {
    id: "f7",
    type: "PROMOTION",
    category: "Moda",
    store: stores.nova,
    images: ["https://picsum.photos/seed/nova-promo-1/800/1000"],
    promotion: {
      label: "20% OFF",
      conditions: "Válido hasta el 30 de septiembre en toda la colección de temporada.",
    },
    product: {
      id: "p1",
      name: "Chaqueta oversize acolchada",
      price: 189000,
      currency: "COP",
      availability: "in_stock",
      rating: 0,
    },
    likes: 47,
  },
  {
    id: "f8",
    type: "PROMOTION",
    category: "Calzado",
    store: stores.terra,
    images: ["https://picsum.photos/seed/terra-promo-1/800/1000"],
    promotion: {
      label: "2x1 en accesorios",
      conditions: "Este fin de semana, en tienda física y por WhatsApp.",
    },
    likes: 31,
  },
  {
    id: "f9",
    type: "COLLECTION",
    category: "Moda",
    store: stores.nova,
    images: ["https://picsum.photos/seed/nova-col-1/800/1000"],
    title: "Temporada Fría",
    collectionId: "c1",
    likes: 58,
  },
  {
    id: "f10",
    type: "COLLECTION",
    category: "Calzado",
    store: stores.terra,
    images: ["https://picsum.photos/seed/terra-col-1/800/1000"],
    title: "Urbana",
    collectionId: "c1",
    likes: 22,
  },
  {
    id: "f11",
    type: "STORE_STORY",
    category: "Tecnología",
    store: stores.orbe,
    images: ["https://picsum.photos/seed/orbe-story-1/800/1000"],
    title: "Conoce nuestro nuevo espacio",
    caption: "Así se ve nuestro punto de soporte técnico esta semana, listo para resolver tus dudas en persona.",
    likes: 64,
  },
  {
    id: "f12",
    type: "STORE_STORY",
    category: "Hogar",
    store: stores.casa,
    images: ["https://picsum.photos/seed/casa-story-1/800/1000"],
    title: "Así trabajamos",
    caption: "Cada vela se vierte y etiqueta a mano en nuestro taller de Medellín, en lotes pequeños.",
    likes: 39,
  },
];
