import type { FeedItem, Store } from "./types";

// Datos mock. Centralizados y tipados para reemplazo directo por Supabase
// cuando exista backend real (ver LOOP_01.md).

export const stores: Record<string, Store> = {
  nova: {
    id: "nova",
    name: "Nova Studio",
    avatarUrl: "https://i.pravatar.cc/64?img=32",
    verified: true,
    distanceKm: 1.2,
    whatsappNumber: "573001234567",
    rating: 4.8,
    followers: 3200,
  },
  luma: {
    id: "luma",
    name: "Luma Perfumería",
    avatarUrl: "https://i.pravatar.cc/64?img=47",
    verified: true,
    distanceKm: 3.8,
    whatsappNumber: "573007654321",
    rating: 4.9,
    followers: 5100,
  },
  terra: {
    id: "terra",
    name: "Terra Calzado",
    avatarUrl: "https://i.pravatar.cc/64?img=15",
    distanceKm: 0.6,
    whatsappNumber: "573009988776",
    rating: 4.5,
    followers: 1800,
  },
  orbe: {
    id: "orbe",
    name: "Órbita Tech",
    avatarUrl: "https://i.pravatar.cc/64?img=60",
    verified: true,
    whatsappNumber: "573005544332",
    rating: 4.7,
    followers: 6400,
  },
  casa: {
    id: "casa",
    name: "Casa Cálida",
    avatarUrl: "https://i.pravatar.cc/64?img=25",
    distanceKm: 5.4,
    whatsappNumber: "573002211334",
    rating: 4.9,
    followers: 940,
  },
};

export const feedItems: FeedItem[] = [
  {
    id: "f1",
    type: "product",
    category: "Moda",
    store: stores.nova,
    images: [
      "https://picsum.photos/seed/nova-jacket-1/800/1000",
      "https://picsum.photos/seed/nova-jacket-2/800/1000",
    ],
    badge: "Nuevo",
    product: {
      id: "p1",
      name: "Chaqueta oversize acolchada",
      price: 189000,
      currency: "COP",
      availability: "in_stock",
      rating: 4.8,
    },
    likes: 214,
  },
  {
    id: "f2",
    type: "social",
    category: "Perfumería",
    store: stores.luma,
    images: ["https://picsum.photos/seed/luma-social-1/800/900"],
    caption:
      "Así se ve nuestro rincón de fragancias en la tienda física esta semana.",
    product: {
      id: "p2",
      name: "Eau de Parfum Ámbar 50ml",
      price: 132000,
      currency: "COP",
      availability: "in_stock",
    },
    likes: 96,
  },
  {
    id: "f3",
    type: "product",
    category: "Calzado",
    store: stores.terra,
    images: [
      "https://picsum.photos/seed/terra-shoes-1/800/1000",
      "https://picsum.photos/seed/terra-shoes-2/800/1000",
      "https://picsum.photos/seed/terra-shoes-3/800/1000",
    ],
    badge: "Pocas unidades",
    product: {
      id: "p3",
      name: "Botas urbanas cuero",
      price: 245000,
      currency: "COP",
      availability: "low_stock",
      rating: 4.6,
    },
    likes: 158,
  },
  {
    id: "f4",
    type: "product",
    category: "Tecnología",
    store: stores.orbe,
    images: ["https://picsum.photos/seed/orbe-tech-1/800/1000"],
    product: {
      id: "p4",
      name: "Audífonos inalámbricos ANC",
      price: 310000,
      currency: "COP",
      availability: "in_stock",
      rating: 4.7,
    },
    likes: 341,
  },
  {
    id: "f5",
    type: "social",
    category: "Hogar",
    store: stores.casa,
    images: ["https://picsum.photos/seed/casa-social-1/800/900"],
    caption: "Nueva colección de velas para diciembre, huelen increíble.",
    product: {
      id: "p5",
      name: "Vela artesanal ámbar y vainilla",
      price: 48000,
      currency: "COP",
      availability: "in_stock",
    },
    likes: 72,
  },
  {
    id: "f6",
    type: "product",
    category: "Moda",
    store: stores.nova,
    images: ["https://picsum.photos/seed/nova-bag-1/800/1000"],
    product: {
      id: "p6",
      name: "Bolso mini estructurado",
      price: 156000,
      currency: "COP",
      availability: "out_of_stock",
      rating: 4.9,
    },
    likes: 289,
  },
];
